### ISSUE TITLE
How are event_id/block IDs determined?

### ISSUE THREAD

**Issue by tejasmanohar** [maxchehab/phelia#17]
How does Phelia come up with event_id/block_ids to match components/events from Slack? Are they generated on `new Phelia`? Are they consistent / always the same if you don't change the React components?

One thing I thought about when pushing updates to other in-Slack Block kit UIs in the past (not App Home's but guessing it applies here, too) is that my backend needs to knows how to handle events from the last version of the code (using their action IDs / block IDs) in case someone is currently interacting with the app.

Is there a story around that here? Doesn't matter much for my current use case but would matter if you cared about not having downtime / functionality break during your deploys

(Please forgive me if this is a silly question, might be missing something obvious)

**Comment by maxchehab** [comment]
Good quesetion, and I have to admin, it's not well documented. Event and Block ID's are specified in the component's props. They are kinda hidden behind an `action` property. For example the following: 

```tsx
 <TextField
  action="summary"
  placeholder="type something here"
  multiline
  />
```

Transforms into:
```json
{
    "type": "plain_text_input",
    "action_id": "summary",
    "multiline": true,
    "placeholder": {
      "type": "plain_text",
      "text": "type something here"
    }
}
```

The `action` prop is required for all actionable components, so it will always be deterministic.

**Comment by tejasmanohar** [comment]
Thanks! This makes sense
