### ISSUE TITLE
Asynchronous data fetching / other effects

### ISSUE THREAD

**Issue by lukasluecke** [maxchehab/phelia#3]
Hey, first of all thank you for releasing this - looks great so far! 🙂 

I have gotten a basic app working now, with some placeholder interactions. Now I would like to show some "live data" in the Home Tab, and was wondering if there was an example for this or if you had any hints. My attempts either resulted in stale state, that was only refreshed after another interaction, or lots of requests triggered that didn't do anything at all 🙈 

Something like "send a GET request on load, fetch data, show result to user". In a normal React app I'd use `useEffect(() => fetch(requestTarget).then(data => setState(data)), [requestTarget])` or something like that and I'd expect that to cause an update of the view. However that didn't seem to work for me 🤔

**Comment by maxchehab** [comment]
@lukasluecke I'll look into this. How does the proposed API suite your needs? 

I think adding an `onLoad` callback to the `<Home/>` component will do the trick. This will let you update the state from within the component whenever the home tab loads.

```tsx
export function HomeApp({ useState }) {
  const [counter, setCounter] = useState("counter", 0);

  return (
    <Home onLoad={(event) => setCounter(counter + 1)}>
      <Section>
        <Text type="mrkdwn">*Counter:* {counter}</Text>
      </Section>
    </Home>
  );
}
```

**Comment by lukasluecke** [comment]
@maxchehab Appreciate the quick response!

Yeah, onLoad would be one case (and would probably solve most of what I currently require) 🙂 However it might be more "react-like" to provide something like the `useEffect()`-hook for this?

I was also thinking about non-user-triggered updates in general, could be a nice addition:
```tsx
export function HomeApp({ useState }) {
  const [counter, setCounter] = useState("counter", 0);

  // time-based updates
  // e.g. https://overreacted.io/making-setinterval-declarative-with-react-hooks/
  useInterval(() => setCounter(counter + 1), 1000);

  // externally triggered updates
  // e.g. https://developer.mozilla.org/en-US/docs/Web/API/EventSource
  useEffect(() => {
    const eventSource = new EventSource('https://my-external-event-source.com/increment');
    eventSource.onmessage = (amount: number) => setCounter(counter + amount);

    return () => eventSource.close();
  }, [])

  return (
    <Home onLoad={(event) => setCounter(0)}>
      <Section>
        <Text type="mrkdwn">*Counter:* {counter} since last reload</Text>
      </Section>
    </Home>
  );
}
```

Having something like the React rendering lifecycle work as in normal web applications would make a lot of things easier to understand for new users I believe. Maybe provide some escape-hatches that stay active after the render and that have access to trigger a rerender with updated state values or something? Maybe like a generator function that is running outside of the render function? 🤔 

Sorry for the ramblings, I'll try and prepare some more concise and considered suggestions over the weekend 🙂

**Comment by maxchehab** [comment]
Thank you so much for your input. I really appreciate it and it's super useful :)

Something like `useEffect` is hard to implement because it is nearly impossible to figure out when exactly the effect has completed.

Using the Home Tab as an example; when Slack sends an `app_home_opened` event Phelia will grab your component from storage, render, and update the home tab.

If we have a `useEffect` that is subscribing to an external data-source Phelia will be unable to recognize when the rendering stage is complete. Essentially it will just hang. This is why I've designed all asynchronous methods to only be sourced from user interaction.

Phelia has been designed to be event driven and serverless compatible. Subscribing to an external data source removes this functionality. I think instead we need a way to update messages or home tabs from external data sources.

Maybe something like:

```ts
const Home = ({ props }) => (
  <Home>
    <Section>
      <Text type="mrkdwn">*Counter:* {props.counter} since last reload</Text>
    </Section>
  </Home>
);

const eventSource = new EventSource('https://event-source.com/increment');
eventSource.onmessage = (amount: number) => client.updateMessage(Home, { counter: amount });
```

**Comment by lukasluecke** [comment]
Yeah I was thinking about how to make those two workflows compatible as well, but I'm not quite sure yet. `useEffect` in React however is also nothing that actually interrupts or postpones the completion of the rendering stage afaik, so I believe there should be a way to handle it here as well.

I'll probably have to dig in to the reconciler you're using to give more practical suggestions 🙈 

But until then I think I'd be content with your `updateMessage` and `onLoad` proposals, these essentially solve the same problems just with a different approach 🙂

**Comment by tejasmanohar** [comment]
Is there a workaround for this in the current state?

I'm rewriting my "App Home" and wanted to use Phelia but checked the GH issues first to make sure it's fit. From reading this issue, it seems that currently, there's no React-y way to render live data when the user opens the App Home (app_home_opened). Is that correct?

Is there a potential workaround with managing the asynchronous activity outside of the scope of the React component (and passing in some sort of ID or something from the component's execution, maybe the latest Slack event's ID? to dedupe).

**Comment by tejasmanohar** [comment]
Do original lifecycle methods work like componentDidUpdate?

**Comment by lukasluecke** [comment]
You might be able to add your own listener inside `slackEvents.on("app_home_opened")` and prepare something, but I'm not sure how convenient that would be.

**Comment by lukasluecke** [comment]
I don't believe the lifecycle methods work, due to the way the components are hydrated and rendered. If you have suggestions on how they could be integrated while preserving the "pureness" of the Phelia handlers, let me know - I'm still looking for a way to get those to work as expected 😅

**Comment by tejasmanohar** [comment]
Don't have ideas right now :\ -- my React experience isn't too advanced TBH

Oh, it looks like there is an `onLoad` inside App Home now? https://github.com/maxchehab/phelia/wiki/Documentation#custom-storage

Should this issue be closed?

**Comment by maxchehab** [comment]
@tejasmanohar I was planning on closing this issue once I add an `updateMessage` function. The Home component's `onLoad` will work for cases where the action is sourced from a component. There is currently no way to update a component from an external source.

**Comment by tejasmanohar** [comment]
Makes sense. I was thinking about that, too. Eg refreshing all the components every X

Is there an API in mind for the updateMessage? Just curious

**Comment by maxchehab** [comment]
I was thinking something along the lines of:

```ts
// store this message key somewhere
const messageKey = await phelia.postMessage(Message, props);
...

await phelia.update(messageKey, newProps);
```
Letting the developer the message props should be sufficient for most
workflows (I imagine).

**Comment by tejasmanohar** [comment]
Ah yeah, that seems reasonable-- can't think of a case that doesn't cover off hand

**Comment by maxchehab** [comment]
Closing this from #19
