### ISSUE TITLE
Step by Step "Getting Started" guide

### ISSUE THREAD

**Issue by hipstersmoothie** [maxchehab/phelia#5]
Right now the docs show you a lot of cool things you can do. What they don't do is show you the path of least resistance getting to a working app. 

I was able to get a repo partially working: https://github.com/hipstersmoothie/phelia-test

But I keep running into this error:

![Screen Shot 2020-04-16 at 9 22 19 AM](https://user-images.githubusercontent.com/1192452/79481014-c7767180-7fc3-11ea-936d-c9b2c53ab664.png)

I think I've given it all the permissions it needs, but it was really unclear from the docs what scopes I should give the bot.

![Screen Shot 2020-04-16 at 9 23 23 AM](https://user-images.githubusercontent.com/1192452/79481122-eecd3e80-7fc3-11ea-8aa7-e754c723aff8.png)

# What do I want?

A step-by-step guide taking me from no project to working slack integration. This should include where to go in the slack settings ui to activate/enable all necessary features.

**Comment by maxchehab** [comment]
I'll work on improving the docs this weekend. In the meantime I took a look at your code sample and everything check out. 

The exception being thrown seems like the channel `@andrew` doesn't exist. Can you verify that it does?

The only scopes that the library depends on are `chat:write` and and optionally `users:read`.

<img width="665" alt="image" src="https://user-images.githubusercontent.com/13038919/79484389-6a30ef00-7fc8-11ea-8700-d42e95ebe437.png">

**Comment by hipstersmoothie** [comment]
`@andrew` isn't a channel it's my user account. Note: I also tried `@Andrew` and it didn't work either.

![Screen Shot 2020-04-16 at 10 01 06 AM](https://user-images.githubusercontent.com/1192452/79484873-32767700-7fc9-11ea-967a-5e6ea5a0083c.png)

**Comment by maxchehab** [comment]
@hipstersmoothie Is the Slack app installed in your workspace? Are you able to open a conversation with the bot?

**Comment by hipstersmoothie** [comment]
I think it's installed.

![Screen Shot 2020-04-16 at 11 41 43 AM](https://user-images.githubusercontent.com/1192452/79494075-40cb8f80-7fd7-11ea-9239-c9de3ac42ca4.png)

**Comment by lukasluecke** [comment]
I also had some issues getting started early on, I'll try to provide some PRs for documentation or example usage soon, provided I find some free time 😅

@hipstersmoothie I just checked the docs at https://api.slack.com/methods/chat.postMessage, and in the part labeled "Post to an IM channel" I found some references to your `channel_not_found` error and the following note:
> We are phasing out support for ambiguously passing a "username" as a channel value. Please always use channel-like IDs instead.

Maybe check out the suggestions there and try if any of them work? 🙂

**Comment by hipstersmoothie** [comment]
I see! That's good to know, it should also be reflected in the docs. maybe `phelia` could provide a way to get IDs for usernames

**Comment by lukasluecke** [comment]
From what I understand so far Phelia focuses more on the interactions and rendering (as a replacement for BlockKit) - you probably need to use some Slack-SDKs for other things anyway, e.g. `@slack/events-api`. For this use-case specifically you probably want `@slack/web-api` (also see https://github.com/slackapi/node-slack-sdk/issues/73#issuecomment-496965102).

I do agree with the docs part though, maybe you can contribute a PR with what would have helped you?

**Comment by hipstersmoothie** [comment]
I would gladly contribute the docs, it's just I have no working code myself yet 😅 

> This framework was created to help you intuitively create Slack applications without needing to know how underlying storage, state, webhooks, or message publishing works

The promise of this library to me was partially that it makes making slack apps easier. If I have to immediately find the underlying library, read slack issues, and figure out all the parts of sending a message to a username, then that "easy experience" is immediately lost. 

Seems like this would be the perfect job for `client.postMessage` to do.

**Comment by lukasluecke** [comment]
Okay so I just tried your example (with your exact code, only using my username - no UserID or anything), and oddly enough it works for me. Could you try re-installing the App to your Slack workspace (and maybe take a screenshot of the OAuth-Screen there)?

I'm wondering what the difference could be.. (I had to add the `chat:write` scope, because that gave me an error first, but you already have that one)

**Comment by hipstersmoothie** [comment]
Re-install

![Screen Shot 2020-04-16 at 3 39 19 PM](https://user-images.githubusercontent.com/1192452/79513335-72088780-7ff8-11ea-9b9c-0c164fa6b3a2.png)

![Screen Shot 2020-04-16 at 3 41 44 PM](https://user-images.githubusercontent.com/1192452/79513477-c7dd2f80-7ff8-11ea-8d8e-d3359db58410.png)

Happy to help debug any way I can

**Comment by lukasluecke** [comment]
Mh okay, could you try enabling the "Incoming Webhooks" Feature, and when reinstalling the App choose the App's own channel (probably `github_teams` for you)?

**Comment by maxchehab** [comment]
I'm creating a community Slack, here is an invite link https://join.slack.com/t/phelia/shared_invite/zt-dm4ln2w5-6aOXvv5ewiifDJGsplcVjA 

Please join and we can debug this a little quicker ;)
