### ISSUE TITLE
Home Page docs out of date

### ISSUE THREAD

**Issue by hipstersmoothie** [maxchehab/phelia#6]
When I try to use the code in the docs 

![Screen Shot 2020-04-17 at 4 59 06 PM](https://user-images.githubusercontent.com/1192452/79622695-22e05680-80cd-11ea-8d3e-d518ba146d60.png)

**Comment by maxchehab** [comment]
This is a problem with the upstream types in `@slacks/events-api`. See https://github.com/slackapi/node-slack-sdk/issues/948

Try either `yarn add @types/node@12.7.0 --dev` or casting `slackEvents` as an `any`.

**Comment by hipstersmoothie** [comment]
Nice that worked. Thanks!

**Comment by maxchehab** [comment]
Sweet!
