### ISSUE TITLE
jsDoc Annotations

### ISSUE THREAD

**Issue by hipstersmoothie** [maxchehab/phelia#8]
I think it would be useful to combine some of your current docs/slacks with the source code for a slightly better developer experience. I am fine with doing of this, here is a sample

![Screen Shot 2020-04-17 at 8 36 13 PM](https://user-images.githubusercontent.com/1192452/79627185-17038d00-80eb-11ea-9928-4e484844bed3.png)

I would also add an eslint rule to ensure that these annotations are always present.

**Comment by maxchehab** [comment]
Great idea 👍
